name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23lib6J3mgA2vBZlgw" # 你的 GitHub OAuth App 的 Client ID
GITHUB_OWNER = "hurricanecorner" # 你的 GitHub 用户名
GITHUB_REPO = "NavSphere" # 你的 GitHub 仓库名
GITHUB_BRANCH = "main" # 你的 GitHub 分支名
NEXTAUTH_URL = "https://navsphere-2vt.pages.dev/api/auth" # Cloudflare Pages 的域名（或者你自定义的域名）加/api/auth
NEXT_PUBLIC_API_URL="https://navsphere-2vt.pages.dev/" # Cloudflare Pages 的域名（或者你自定义的域名）

